// fa-angular/src/app/components/navigation/utility-nav-popup/settings/settings.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatIconModule } from '@angular/material/icon';
import { MatRippleModule } from '@angular/material/core';

interface SettingMenuItem {
  icon: string;
  title: string;
  description: string;
  link?: string;
  external?: boolean;
  separator?: boolean;
}

@Component({
  selector: 'app-settings-content',
  standalone: true,
  imports: [CommonModule, MatIconModule, MatRippleModule],
  styleUrls: ['./settings.component.scss'],
  template: `
    <div class="settings-container">
      <ul class="settings-menu">
        <ng-container *ngFor="let item of settings">
          <li>
            <button
              matRipple
              class="menu-item"
            >
              <mat-icon>{{
                item.icon
              }}</mat-icon>
              <div class="flex-grow">
                <div class="font-bold">
                  <span>{{ item.title }}</span>
                  <mat-icon *ngIf="item.external">open_in_new</mat-icon
                  >
                </div>
                <div class="description">
                  {{ item.description }}
                </div>
              </div>
            </button>
          </li>
          <hr *ngIf="item.separator" class="separator" />
        </ng-container>
      </ul>
    </div>
  `,
})
export class SettingsContentComponent {
  settings: SettingMenuItem[] = [
    {
      icon: 'apps',
      title: 'My Platform',
      description: 'Manage Integrations',
      external: true,
    },
    {
      icon: 'business',
      title: 'My Company',
      description: 'Billing, Plan, Users, Banking',
      external: true,
      separator: true,
    },
    {
      icon: 'description',
      title: 'Document',
      description: 'Templates, Numbering, Customization',
    },
    {
      icon: 'assessment',
      title: 'Accounting',
      description: 'Methods, Periods, Opening Balance',
    },
    {
      icon: 'person',
      title: 'User Settings',
      description: 'Profile, Preferences, Manage Users',
      external: true,
    },
    {
      icon: 'inventory_2',
      title: 'Products Setting',
      description: 'Warehouses, Categories, Units',
    },
  ];
}

// flowaccount-ui/src/components/utility-menu/Settings.tsx
import React from "react";
import {
  FileText,
  BarChart2,
  Users,
  Box,
  LayoutGrid,
  Building,
  ExternalLink,
} from "lucide-react";

const settingsItems = [
  {
    icon: <LayoutGrid size={20} className="text-gray-500" />,
    title: "MyPlatform",
    subtitle: "Manage Integrations",
    external: true,
    separator: false,
  },
  {
    icon: <Building size={20} className="text-gray-500" />,
    title: "My Company",
    subtitle: "Billing, Plan, Users, Banking",
    external: true,
    separator: false,
  },
  {
    icon: <FileText size={20} className="text-gray-500" />,
    title: "Document",
    subtitle: "Templates, Numbering, Customization",
    external: false,
    separator: true,
  },
  {
    icon: <BarChart2 size={20} className="text-gray-500" />,
    title: "Accounting",
    subtitle: "Methods, Periods, Opening Balance",
    external: false,
    separator: false,
  },
  {
    icon: <Users size={20} className="text-gray-500" />,
    title: "User Settings",
    subtitle: "Profile, Preferences, Manage Users",
    external: true,
    separator: false,
  },
  {
    icon: <Box size={20} className="text-gray-500" />,
    title: "Products Setting",
    subtitle: "Warehouses, Categories, Units",
    external: false,
    separator: false,
  },
];

const titleStyle = "font-semibold text-sm text-gray-800";
const subtitleStyle = "text-xs text-gray-500";

const Settings = () => {
  return (
    <div className="flex flex-col gap-1" style={{ width: "320px" }}>
      {settingsItems.map((item) => (
        <div
          key={item.title}
          className={`flex items-center p-2 rounded-xl cursor-pointer hover:bg-gray-100 ${
            item.separator ? "border-t border-gray-200 mt-1 pt-3" : ""
          }`}
        >
          <div className="w-8 h-8 flex items-center justify-center mr-3">
            {item.icon}
          </div>
          <div className="flex-grow">
            <div className="flex items-center">
              <p className={titleStyle}>{item.title}</p>
              {item.external && (
                <ExternalLink size={14} className="ml-2 text-gray-400" />
              )}
            </div>
            <p className={subtitleStyle}>{item.subtitle}</p>
          </div>
        </div>
      ))}
    </div>
  );
};

export default Settings;
