// flowaccount-ui/src/components/utility-menu/Apps.tsx
import React from "react";
import Image from "next/image";
import logoFA from "../../../public/logo_fa_small.png";
import logoPayroll from "../../../public/logo_payroll_small.png";
import logoAutoKey from "../../../public/logo_autokey_small.png";

const apps = [
  {
    name: "FlowAccount",
    subtitle: "Easy Accounting",
    icon: <Image src={logoFA} alt="FlowAccount" width={30} height={30} />,
  },
  {
    name: "Payroll",
    subtitle: "Manage Pay",
    icon: <Image src={logoPayroll} alt="Payroll" width={30} height={30} />,
  },
  {
    name: "AutoKey",
    subtitle: "AI Document Scanner",
    icon: <Image src={logoAutoKey} alt="AutoKey" width={30} height={30} />,
  },
];

const titleStyle = "font-semibold text-sm text-gray-800";
const subtitleStyle = "text-xs text-gray-500";

const Apps = () => {
  return (
    <div className="flex flex-col gap-1" style={{ width: "220px" }}>
      {apps.map((app) => (
        <div
          key={app.name}
          className="flex items-center p-2 rounded-xl hover:bg-gray-100 cursor-pointer"
        >
          <div className="w-10 h-10 rounded-lg flex items-center justify-center mr-3">
            {app.icon}
          </div>
          <div>
            <p className={titleStyle}>{app.name}</p>
            <p className={subtitleStyle}>{app.subtitle}</p>
          </div>
        </div>
      ))}
    </div>
  );
};

export default Apps;

// fa-angular/src/app/components/navigation/utility-nav-popup/apps/apps.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-apps-content',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="p-1">
      <a href="#" class="app-item">
        <img src="assets/logo_fa_small.png" alt="FlowAccount logo" />
        <div>
          <div class="app-title">FlowAccount</div>
          <div class="app-subtitle">Easy Accounting</div>
        </div>
      </a>
      <a href="#" class="app-item">
        <img src="assets/logo_payroll_small.png" alt="Payroll logo" />
        <div>
          <div class="app-title">Payroll</div>
          <div class="app-subtitle">Manage Pay</div>
        </div>
      </a>
      <a href="#" class="app-item">
        <img src="assets/logo_autokey_small.png" alt="AutoKey logo" />
        <div>
          <div class="app-title">AutoKey</div>
          <div class="app-subtitle">AI Document Scanner</div>
        </div>
      </a>
    </div>
  `,
  styles: [
    `
      .app-item {
        display: flex;
        align-items: center;
        padding: 0.75rem; /* 12px */
        border-radius: 1.3rem; /* 8px */
        transition: background-color 0.2s;
        text-decoration: none;
        color: inherit;
      }
      .app-item:hover {
        background-color: #f3f4f6; /* gray-100 */
      }
      .app-item img {
        width: 32px;
        height: 32px;
        margin-right: 1rem; /* 16px */
      }
      .app-title {
        font-weight: 600;
        font-size: 0.875rem; /* 14px */
        line-height: 1.25rem;
      }
      .app-subtitle {
        font-size: 0.75rem; /* 12px */
        line-height: 1rem;
        color: #6b7280; /* gray-500 */
      }
    `,
  ],
})
export class AppsContentComponent {}
