// flowaccount-ui/src/components/MainMenu.tsx
import InsertChartIcon from "@mui/icons-material/InsertChart";
import { mainMenu, bottomMenu, MenuItem } from "./menuData";

interface MainMenuProps {
  mainMenu?: MenuItem[];
  bottomMenu?: MenuItem[];
  selectedMenu?: string;
  onSelectMenu?: (label: string) => void;
}

export default function MainMenu({
  mainMenu: mainMenuProp,
  bottomMenu: bottomMenuProp,
  selectedMenu,
  onSelectMenu,
}: MainMenuProps) {
  const main = mainMenuProp || mainMenu;
  const bottom = bottomMenuProp || bottomMenu;
  return (
    <aside className="w-56 flex flex-col justify-between py-8 px-0 bg-gradient-to-b from-blue-500 to-blue-400 text-white shadow-lg">
      <div>
        <div className="flex flex-col items-center mb-8">
          <div className="bg-white bg-opacity-20 rounded-full p-4 mb-6">
            <InsertChartIcon fontSize="large" sx={{ fill: "white" }} />
          </div>
        </div>
        <nav className="flex flex-col gap-2">
          {main.map((item) => (
            <a
              key={item.label}
              href="#"
              onClick={(e) => {
                e.preventDefault();
                onSelectMenu?.(item.label);
              }}
              className={`flex items-center gap-4 px-4 py-3 rounded-lg transition-all font-medium text-base ${
                selectedMenu === item.label
                  ? "bg-white bg-opacity-20 text-white"
                  : "hover:bg-white hover:bg-opacity-10 text-white/90"
              }`}
            >
              <span>{item.icon}</span>
              <span>{item.label}</span>
            </a>
          ))}
        </nav>
      </div>
      <div className="flex flex-col gap-2 mb-4">
        {bottom.map((item) => (
          <a
            key={item.label}
            href="#"
            className="flex items-center gap-4 px-4 py-3 rounded-lg transition-all font-medium text-base hover:bg-white hover:bg-opacity-10 relative"
          >
            <span>{item.icon}</span>
            <span>{item.label}</span>
            {item.notification && (
              <span className="absolute right-4 top-3 w-3 h-3 bg-red-500 rounded-full border-2 border-white"></span>
            )}
          </a>
        ))}
      </div>
    </aside>
  );
}

// fa-angular/src/app/components/navigation/main-menu/main-menu.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { MenuItem } from '../../../models/menu.models';

@Component({
  selector: 'app-main-menu',
  standalone: true,
  imports: [CommonModule, RouterModule],
  template: `
    <div
      class="fixed left-0 top-0 h-screen bg-white border-r border-gray-200 z-50 transition-all duration-300"
      [class.w-16]="isCollapsed"
      [class.w-25]="!isCollapsed"
    >
      <!-- Logo section -->
      <div class="p-4 border-b border-gray-200">
        <div class="flex items-center justify-center">
          <span class="text-xl font-bold text-blue-600" *ngIf="!isCollapsed"
            >FA</span
          >
          <span class="text-sm font-bold text-blue-600" *ngIf="isCollapsed"
            >F</span
          >
        </div>
      </div>

      <!-- Main menu items -->
      <nav class="mt-6 flex-1">
        <div class="space-y-1 px-2">
          <button
            *ngFor="let item of mainMenu"
            (click)="onSelectMenu(item.label)"
            (mouseenter)="onMainMenuHover(item.label)"
            (mouseleave)="onMainMenuHover(undefined)"
            [class]="getMenuItemClasses(item.label)"
            class="w-full flex items-center px-3 py-2 text-sm font-medium rounded-md transition-colors duration-200"
          >
            <span class="text-base mr-3" *ngIf="item.icon">{{
              item.icon
            }}</span>
            <span *ngIf="!isCollapsed">{{ item.label }}</span>
          </button>
        </div>
      </nav>

      <!-- Bottom menu items -->
      <div
        class="absolute bottom-0 left-0 right-0 p-2 border-t border-gray-200"
      >
        <div class="space-y-1">
          <button
            *ngFor="let item of bottomMenu"
            (mouseenter)="onUtilityMenuHover()"
            class="w-full flex items-center px-3 py-2 text-sm font-medium text-gray-600 rounded-md hover:bg-gray-100 hover:text-gray-900 transition-colors duration-200"
          >
            <span class="text-base mr-3" *ngIf="item.icon">{{
              item.icon
            }}</span>
            <span *ngIf="!isCollapsed">{{ item.label }}</span>
          </button>
        </div>
      </div>
    </div>
  `,
  styleUrls: ['./main-menu.component.scss'],
})
export class MainMenuComponent {
  @Input() mainMenu: MenuItem[] = [];
  @Input() bottomMenu: MenuItem[] = [];
  @Input() selectedMenu = '';
  @Input() isCollapsed = false;
  @Input() hoveredMenu: string | null = null;

  @Output() selectMenu = new EventEmitter<string>();
  @Output() mainMenuHover = new EventEmitter<string | undefined>();
  @Output() utilityMenuHover = new EventEmitter<void>();

  onSelectMenu(label: string) {
    this.selectMenu.emit(label);
  }

  onMainMenuHover(label: string | undefined) {
    this.mainMenuHover.emit(label);
  }

  onUtilityMenuHover() {
    this.utilityMenuHover.emit();
  }

  getMenuItemClasses(label: string): string {
    const isSelected = this.selectedMenu === label;
    const isHovered = this.hoveredMenu === label;

    let classes = '';

    if (isSelected) {
      classes += 'bg-blue-100 text-blue-900 border-blue-300';
    } else if (isHovered) {
      classes += 'bg-gray-100 text-gray-900';
    } else {
      classes += 'text-gray-600 hover:bg-gray-100 hover:text-gray-900';
    }

    return classes;
  }
}
